#################################################################################
##                ____                             __  __  ____                ##
##_______________|  _ \ ___   ___  _ __   ___ _ __|  \/  |/ ___|_______________##
##_______________| |_) / _ \ / _ \| '_ \ / _ \ '__| |\/| | |    _______________##
##_______________|  __/ (_) | (_) | |_) |  __/ |  | |  | | |___ _______________##
##_______________|_|   \___/ \___/| .__/ \___|_|  |_|  |_|\____|_______________##
##                           Main |_| Configuration                            ##
##                                                                             ##
##        WEBSITE:       https://marcpg.com/pooper                             ##
##        SOURCE-CODE:   https://github.com/MarcPG1905/PooperMC                ##
##        BUGS & ISSUES: https://github.com/MarcPG1905/PooperMC/issues         ##
##                                                                             ##
#################################################################################




## Moderators-Only Discord Webhook ##
# A Discord webhook URL, that's only accessible by moderators.
# All moderation-related messages like bans, kicks etc. are sent to this webhook.
# If the link is invalid or just no link at all, this module will be disabled!
moderator-webhook: https://discord.com/api/webhooks/...


## Should Translations Be Enabled? ##
# Defines if translations are enable and should be downloaded.
enable-translations: true


## GameMode-Related Configuration ##
# Gamemodes should follow the simple scheme:
#   prefix: max-players
# Prefix: The prefix of all servers hosting this game mode.
# Max-Players: The maximum amount of players on each server.
gamemodes:
  game1: 2
  game2: 10


## Should the Chat be global on the whole Proxy? ##
# If set to true, all messages will be sent to everyone on the whole proxy,
# instead of only everyone on the player's backend server.
global-chat: false


## If the Whitelist is Enabled ##
whitelist-enabled: false


## The method to store the data. ##
#   Available Methods:
#     | -> database  : recommended
#     | -> yaml      : default (.yml)
#     | -> ram       : not recommended, restarting will erase data
storage-method: yaml




##  -------------------------------------------------------------------------  ##
##                 ___         _          _                                    ##
##                |   \  __ _ | |_  __ _ | |__  __ _  ___ ___                  ##
##                | |) |/ _` ||  _|/ _` || '_ \/ _` |(_-</ -_)                 ##
##                |___/ \__,_| \__|\__,_||_.__/\__,_|/__/\___|                 ##
##                     Everything related to the Database!                     ##
##            (only important if storage-method is set to database)            ##
##  -------------------------------------------------------------------------  ##
database:

  # The type of database.
  #   Available Types:
  #     |-> postgresql    : recommended
  #     |-> mariadb       : preferred over mysql
  #     |-> mysql         :
  #     |-> ms_sql_server : = Microsoft SQL Server
  #     |-> oracle        :
  type: postgresql

  # The address/ip of the database. Can be localhost.
  address: localhost

  # The port of the database. If set to 0, will use the database's default port.
  port: 0

  # The name of the database.
  database: database_name

  # The database login credentials.
  user: username
  passwd: password




##  -------------------------------------------------------------------------  ##
##       __  __                          _                   _                 ##
##      |  \/  |___ ______ __ _ __ _ ___| |   ___  __ _ __ _(_)_ _  __ _       ##
##      | |\/| / -_|_-<_-</ _` / _` / -_) |__/ _ \/ _` / _` | | ' \/ _` |      ##
##      |_|  |_\___/__/__/\__,_\__, \___|____\___/\__, \__, |_|_||_\__, |      ##
##                             |___/              |___/|___/       |___/       ##
##                     All Message-Logging Related Config!                     ##
##  -------------------------------------------------------------------------  ##
message-logging:

  # If the message logging module is enabled or not.
  enabled: true

  # How many messages are stored for each player.
  # A length of about 20 000 will result in 1MB/Player on average.
  # Default is 50 (~2.5KB/Player)
  max-history: 50




##  -------------------------------------------------------------------------  ##
##          ___  _           _         _   _  _    _  _  _  _                  ##
##         / __|| |_   __ _ | |_  ___ | | | || |_ (_)| |(_)| |_  _  _          ##
##        | (__ | ' \ / _` ||  _||___|| |_| ||  _|| || || ||  _|| || |         ##
##         \___||_||_|\__,_| \__|      \___/  \__||_||_||_| \__| \_, |         ##
##                          All Chat-Related Features!           |__/          ##
##  -------------------------------------------------------------------------  ##
chatutility:

  # If the ChatUtility module is enabled or not.
  enabled: true

  # Chat color related configuration.
  # Only works if global-chat is enabled.
  colors:

    # Enables or disables colors in the chat.
    enabled: true

    # If text styles like bold, italic, underlines, etc. should be enabled.
    styles: false

    # If colors in chat will require the poo.chat.colors permission.
    permission: false

  # Chat mentions/pings related configuration.
  mentions:

    # Enables or disables mentions/pings in the chat.
    enabled: true

    # If mentioning players in chat will require the poo.chat.mention permission.
    permission: false

    # Using @everyone in chat, which will mention/ping everyone currently online.
    everyone:

      # Enables or disables the use of @everyone.
      enabled: true

      # If using @everyone in chat will require the poo.chat.mention.everyone permission.
      # Highly recommended, as it can be very annoying when not being limited.
      permission: true




##  -------------------------------------------------------------------------  ##
##             ___                                _     _      _               ##
##            / __| ___  _ _ __ __ ___  _ _  ___ | |   (_) ___| |_             ##
##            \__ \/ -_)| '_|\ V // -_)| '_||___|| |__ | |(_-<|  _|            ##
##            |___/\___||_|   \_/ \___||_|       |____||_|/__/ \__|            ##
##                   All Features shown in your Server-List!                   ##
##  -------------------------------------------------------------------------  ##
server-list:

  # If the ServerList module is enabled or not.
  enabled: true

  # Sets if a custom MotD (Message of the Day) is enabled.
  custom-motd: false

  # A list of all possible MotD that can be shown to the user, if custom-motd is enabled.
  # You can use the MiniMessage syntax for custom styling: https://docs.advntr.dev/minimessage/format.html
  # If you only want one MotD, just put make this only contain that one MotD.
  custom-motd-messages:
    - "A simple MotD without any formatting!"
    - "<yellow>Another <red>example <black>MotD, <green>but <blue>with <white>colors."
    - "A third example with <rainbow>a fancy rainbow</rainbow>. You can add as many as you want."

  # Sets if custom favicons (server icons) are enabled.
  # Custom favicons are currently unstable and experimental. Use at your own risk!
  custom-favicon: false

  # A list of all possible favicons (server icons) that can be shown to the user, if custom-favicon is enabled.
  # Resolution has to be 64x64 pixels. Favicons can currently only be from URLs. You can use services like Dropbox.
  # If you only want one favicon, just put make this only contain that one favicon URL.
  custom-favicon-urls:
    - https://marcpg.com/pooper/example_server-icon.png

  # Sets the maximum player count that should be shown.
  #   Set to -1 to pass through velocity's max players. (Default)
  #   Set to -2 to always show the current player count + 1.
  show-max-players: -1

  # Sets a fake player count that should be shown. Shouldn't be used on honest servers.
  # Can seriously harm your server community's trust!
  #   Set to -1 to pass through velocity's real player count. (Default)
  #   Set to -2 to hide the player count.
  show-current-players: -1




## DO NOT CHANGE THIS! ##
version: 6
