#################################################################################
##                ____                             __  __  ____                ##
##_______________|  _ \ ___   ___  _ __   ___ _ __|  \/  |/ ___|_______________##
##_______________| |_) / _ \ / _ \| '_ \ / _ \ '__| |\/| | |    _______________##
##_______________|  __/ (_) | (_) | |_) |  __/ |  | |  | | |___ _______________##
##_______________|_|   \___/ \___/| .__/ \___|_|  |_|  |_|\____|_______________##
##                           Main |_| Configuration                            ##
##                                                                             ##
##        WEBSITE:       https://marcpg.com/pooper                             ##
##        SOURCE-CODE:   https://github.com/MarcPG1905/PooperMC                ##
##        BUGS & ISSUES: https://github.com/MarcPG1905/PooperMC/issues         ##
##                                                                             ##
#################################################################################




## Moderators-Only Discord Webhook ##
# A Discord webhook URL, that's only accessible by moderators.
# All moderation-related messages like bans, kicks etc. are sent to this webhook.
# If the link is invalid or just no link at all, will disable this module!
moderator-webhook: https://discord.com/api/webhooks/...


## Should Translations Be Enabled? ##
# Defines if translations are enable and should be downloaded.
enable-translations: true


## The method to store the data. ##
#   Available Methods:
#     | -> database  : recommended
#     | -> yaml      : default (.yml)
#     | -> ram       : not recommended, restarting will erase data
storage-method: yaml




##  -------------------------------------------------------------------------  ##
##                 ___         _          _                                    ##
##                |   \  __ _ | |_  __ _ | |__  __ _  ___ ___                  ##
##                | |) |/ _` ||  _|/ _` || '_ \/ _` |(_-</ -_)                 ##
##                |___/ \__,_| \__|\__,_||_.__/\__,_|/__/\___|                 ##
##                     Everything related to the Database!                     ##
##            (only important if storage-method is set to database)            ##
##  -------------------------------------------------------------------------  ##
database:

  # The type of database.
  #   Available Types:
  #     |-> postgresql    : recommended
  #     |-> mariadb       : preferred over mysql
  #     |-> mysql         :
  #     |-> ms_sql_server : = Microsoft SQL Server
  #     |-> oracle        :
  type: postgresql

  # The address/ip of the database. Can be localhost.
  address: localhost

  # The port of the database. If set to 0, will use the database's default port.
  port: 0

  # The name of the database.
  database: database_name

  # The database login credentials.
  user: username
  passwd: password




##  -------------------------------------------------------------------------  ##
##       __  __                          _                   _                 ##
##      |  \/  |___ ______ __ _ __ _ ___| |   ___  __ _ __ _(_)_ _  __ _       ##
##      | |\/| / -_|_-<_-</ _` / _` / -_) |__/ _ \/ _` / _` | | ' \/ _` |      ##
##      |_|  |_\___/__/__/\__,_\__, \___|____\___/\__, \__, |_|_||_\__, |      ##
##                             |___/              |___/|___/       |___/       ##
##                     All Message-Logging Related Config!                     ##
##  -------------------------------------------------------------------------  ##
message-logging:

  # If the message logging module is enabled or not.
  enabled: true

  # How many messages are stored for each player.
  # A length of about 20 000 will result in 1MB/Player on average.
  # Default is 50 (~2.5KB/Player)
  max-history: 50




##  -------------------------------------------------------------------------  ##
##          ___  _           _         _   _  _    _  _  _  _                  ##
##         / __|| |_   __ _ | |_  ___ | | | || |_ (_)| |(_)| |_  _  _          ##
##        | (__ | ' \ / _` ||  _||___|| |_| ||  _|| || || ||  _|| || |         ##
##         \___||_||_|\__,_| \__|      \___/  \__||_||_||_| \__| \_, |         ##
##                          All Chat-Related Features!           |__/          ##
##  -------------------------------------------------------------------------  ##
chatutility:

  # If the ChatUtility module is enabled or not.
  enabled: true

  # Chat color related configuration.
  # Only works if global-chat is enabled.
  colors:

    # Enables or disables colors in the chat.
    enabled: true

    # If text styles like bold, italic, underlines, etc. should be enabled.
    styles: false

    # If colors in chat will require the poo.chat.colors permission.
    permission: false

  # Chat mentions/pings related configuration.
  mentions:

    # Enables or disables mentions/pings in the chat.
    enabled: true

    # If mentioning players in chat will require the poo.chat.mention permission.
    permission: false

    # Using @everyone in chat, which will mention/ping everyone currently online.
    everyone:

      # Enables or disables the use of @everyone.
      enabled: true

      # If using @everyone in chat will require the poo.chat.mention.everyone permission.
      # Highly recommended, as it can be very annoying when not being limited.
      permission: true




##  -------------------------------------------------------------------------  ##
##             ___                                _     _      _               ##
##            / __| ___  _ _ __ __ ___  _ _  ___ | |   (_) ___| |_             ##
##            \__ \/ -_)| '_|\ V // -_)| '_||___|| |__ | |(_-<|  _|            ##
##            |___/\___||_|   \_/ \___||_|       |____||_|/__/ \__|            ##
##                   All Features shown in your Server-List!                   ##
##  -------------------------------------------------------------------------  ##
server-list:

  # If the ServerList module is enabled or not.
  enabled: true

  # Sets if a custom MotD (Message of the Day) is enabled.
  custom-motd: false

  # A list of all possible MotD that can be shown to the user, if custom-motd is enabled.
  # You can use the MiniMessage syntax for custom styling: https://docs.advntr.dev/minimessage/format.html
  # If you only want one MotD, just put make this only contain that one MotD.
  custom-motd-messages:
    - "A simple MotD without any formatting!"
    - "<yellow>Another <red>example <black>MotD, <green>but <blue>with <white>colors."
    - "A third example with <rainbow>a fancy rainbow</rainbow>. You can add as many as you want."

  # Sets if custom favicons (server icons) are enabled.
  # Custom favicons are currently unstable and experimental. Use at your own risk!
  custom-favicon: false

  # A list of all possible favicons (server icons) that can be shown to the user, if custom-favicon is enabled.
  # Resolution has to be 64x64 pixels. Favicons can currently only be from URLs. You can use services like Dropbox.
  # If you only want one favicon, just put make this only contain that one favicon URL.
  custom-favicon-urls:
    - https://marcpg.com/pooper/example_server-icon.png

  # Sets the maximum player count that should be shown.
  #   Set to -1 to pass through velocity's max players. (Default)
  #   Set to -2 to always show the current player count + 1.
  show-max-players: -1

  # Sets a fake player count that should be shown. Shouldn't be used on honest servers.
  # Can seriously harm your server community's trust!
  #   Set to -1 to pass through velocity's real player count. (Default)
  #   Set to -2 to hide the player count.
  show-current-players: -1




##  -------------------------------------------------------------------------  ##
##                     __  __          _        _                              ##
##                    |  \/  | ___  __| | _  _ | | ___  ___                    ##
##                    | |\/| |/ _ \/ _` || || || |/ -_)(_-<                    ##
##                    |_|  |_|\___/\__,_| \_,_||_|\___|/__/                    ##
##                Completely optional and configurable modules.                ##
##  -------------------------------------------------------------------------  ##
modules:

  # ------------------------------------------------------------------------- #
  #                                VEIN MINING                                #
  #           Break one block of a vein and destroy the whole vein.           #
  # ------------------------------------------------------------------------- #
  vein-mining:

    # If the Vein-Mining module is enabled or not.
    enabled: false

    # Sets if you will need to use the right tool, for the vein mining to work.
    require-proper-tool: true

    # Sets if the vein will be destroyed with a little animation, which just
    # makes the blocks be destroyed with a little delay between each block.
    animated: true

    # The maximum distance (radius) in blocks from the initially broken block
    # that the vein will be destroyed.
    max-distance: 10

    # If this is enabled, all default ores in Minecraft will automatically be
    # added to the 'ores' list. This contains all materials ending with "_ore".
    auto-fill-ores: true

    # A list of all materials that will be counted as a vein. See 'auto-fill'!
    # Materials here should NOT contain the namespace (e.g. "minecraft:")!
    ores:
      - example_ore

  # ------------------------------------------------------------------------- #
  #                              NO ANVIL XP CAP                              #
  #            Removes the Anvil XP Cap when enchanting/repairing.            #
  # ------------------------------------------------------------------------- #
  no-anvil-cap: false

  # ------------------------------------------------------------------------- #
  #                         GLOBAL/SHARED ENDER CHEST                         #
  #       Adds a global ender chest that is shared between all players.       #
  # ------------------------------------------------------------------------- #
  global-ender-chest: false

  # ------------------------------------------------------------------------- #
  #                               DEATH BANNING                               #
  #        Bans players automatically whenever they die or get killed.        #
  # ------------------------------------------------------------------------- #
  death-banning:

    # If the Death-Banning module is enabled or not.
    enabled: false

    # Will only ban a player if they got killed by someone else and ignore
    # the death, if it was caused by something else.
    only-killing: false

    # If the death message should be included in the ban/kick screen.
    show-death-message: true

    # How long the player will be banned for. Should only use one time unit.
    #   Set to "kick" to kick instead of ban.
    #   Set to "permanent" to ban permanently.
    duration: 1h

  # ------------------------------------------------------------------------ #
  #                                  MOB AI                                  #
  #           Slightly improves the AI of most mobs on the server.           #
  # ------------------------------------------------------------------------ #
  better-mob-ai:

    # If the Better-Mob-AI module is enabled or not.
    enabled: false

    # Makes groups of friendly mobs, like cows or sheep, all be alerted
    # and flee together, if one of them gets hit.
    panicking-groups: true

  # ------------------------------------------------------------------------ #
  #                                CUSTOM AFK                                #
  #           Very simple, but yet customizable custom AFK system.           #
  # ------------------------------------------------------------------------ #
  # Still experimental without much configuration or additional support.
  custom-afk:

    # If the Custom-AFK module is enabled or not.
    enabled: false

  # ------------------------------------------------------------------------ #
  #                          UTILITY BLOCK COMMANDS                          #
  #   Allows players to open utility blocks without needing to place them.   #
  # ------------------------------------------------------------------------ #
  utility-block-commands:

    # If the Utility-Block-Commands module is enabled or not.
    enabled: false

    # Allows usage of /anvil, which will open an anvil.
    anvil: true

    # Allows usage of /cartography, which will open a cartography table.
    cartography-table: true

    # Allows usage of /workbench or /crafting, which will open a workbench/crafting-table.
    workbench: true

    # Allows usage of /grindstone, which will open a grindstone.
    grindstone: true

    # Allows usage of /loom, which will open a loom.
    loom: true

    # Allows usage of /smithing, which will open a smithing table.
    smithing-table: true

    # Allows usage of /stonecutter, which will open a stonecutter.
    stonecutter: true

    # Allows usage of /enchanting, which will open an enchanting table.
    enchanting: true

    # Allows usage of /ender-chest or /ec, which will open the player's ender chest.
    ender-chest: true

    # Allows usage of /trash, which will open a trash inventory, which will delete all items in it when closed.
    trash: true




## DO NOT CHANGE THIS! ##
version: 9
