#################################################################################
##                ____                             __  __  ____                ##
##_______________|  _ \ ___   ___  _ __   ___ _ __|  \/  |/ ___|_______________##
##_______________| |_) / _ \ / _ \| '_ \ / _ \ '__| |\/| | |    _______________##
##_______________|  __/ (_) | (_) | |_) |  __/ |  | |  | | |___ _______________##
##_______________|_|   \___/ \___/| .__/ \___|_|  |_|  |_|\____|_______________##
##                           Main |_| Configuration                            ##
##                                                                             ##
##        WEBSITE:       https://marcpg.com/poopermc                           ##
##        SOURCE-CODE:   https://github.com/MarcPG1905/PooperMC                ##
##        BUGS & ISSUES: https://github.com/MarcPG1905/PooperMC/issues         ##
##                                                                             ##
#################################################################################




## Moderators-Only Discord Webhook ##
# A Discord webhook URL, that's only accessible by moderators.
# All moderation-related messages like bans, kicks etc. are sent to this webhook.
# If the link is invalid or just no link at all, will disable this module!
moderator-webhook: https://discord.com/api/webhooks/...


## Should Translations Be Enabled? ##
# Defines if translations are enable and should be downloaded.
enable-translations: true


## The method to store the data. ##
#   Available Methods:
#     | -> database  : recommended
#     | -> yaml      : default (.yml)
#     | -> ram       : not recommended, restarting will erase data
storage-method: yaml




##  -------------------------------------------------------------------------  ##
##                 ___         _          _                                    ##
##                |   \  __ _ | |_  __ _ | |__  __ _  ___ ___                  ##
##                | |) |/ _` ||  _|/ _` || '_ \/ _` |(_-</ -_)                 ##
##                |___/ \__,_| \__|\__,_||_.__/\__,_|/__/\___|                 ##
##                     Everything related to the Database!                     ##
##            (only important if storage-method is set to database)            ##
##  -------------------------------------------------------------------------  ##
database:

  # The type of database.
  #   Available Types:
  #     |-> postgresql    : recommended
  #     |-> mariadb       : preferred over mysql
  #     |-> mysql         :
  #     |-> ms_sql_server : = Microsoft SQL Server
  #     |-> oracle        :
  type: postgresql

  # The address/ip of the database. Can be localhost.
  address: localhost

  # The port of the database. If set to 0, will use the database's default port.
  port: 0

  # The name of the database.
  database: database_name

  # The database login credentials.
  user: username
  passwd: password




##  -------------------------------------------------------------------------  ##
##       __  __                          _                   _                 ##
##      |  \/  |___ ______ __ _ __ _ ___| |   ___  __ _ __ _(_)_ _  __ _       ##
##      | |\/| / -_|_-<_-</ _` / _` / -_) |__/ _ \/ _` / _` | | ' \/ _` |      ##
##      |_|  |_\___/__/__/\__,_\__, \___|____\___/\__, \__, |_|_||_\__, |      ##
##                             |___/              |___/|___/       |___/       ##
##                     All Message-Logging Related Config!                     ##
##  -------------------------------------------------------------------------  ##
message-logging:

  # If the message logging module is enabled or not.
  enabled: true

  # How many messages are stored for each player.
  # A length of about 20 000 will result in 1MB/Player on average.
  # Default is 50 (~2.5KB/Player)
  max-history: 50




##  -------------------------------------------------------------------------  ##
##          ___  _           _         _   _  _    _  _  _  _                  ##
##         / __|| |_   __ _ | |_  ___ | | | || |_ (_)| |(_)| |_  _  _          ##
##        | (__ | ' \ / _` ||  _||___|| |_| ||  _|| || || ||  _|| || |         ##
##         \___||_||_|\__,_| \__|      \___/  \__||_||_||_| \__| \_, |         ##
##                          All Chat-Related Features!           |__/          ##
##  -------------------------------------------------------------------------  ##
chatutility:

  # If the ChatUtility module is enabled or not.
  enabled: true

  # Chat color related configuration.
  # Only works if global-chat is enabled.
  colors:

    # Enables or disables colors in the chat.
    enabled: true

    # If text styles like bold, italic, underlines, etc. should be enabled.
    styles: false

    # If colors in chat will require the poo.chat.colors permission.
    permission: false

  # Chat mentions/pings related configuration.
  mentions:

    # Enables or disables mentions/pings in the chat.
    enabled: true

    # If mentioning players in chat will require the poo.chat.mention permission.
    permission: false

    # Using @everyone in chat, which will mention/ping everyone currently online.
    everyone:

      # Enables or disables the use of @everyone.
      enabled: true

      # If using @everyone in chat will require the poo.chat.mention.everyone permission.
      # Highly recommended, as it can be very annoying when not being limited.
      permission: true




##  -------------------------------------------------------------------------  ##
##             ___                                _     _      _               ##
##            / __| ___  _ _ __ __ ___  _ _  ___ | |   (_) ___| |_             ##
##            \__ \/ -_)| '_|\ V // -_)| '_||___|| |__ | |(_-<|  _|            ##
##            |___/\___||_|   \_/ \___||_|       |____||_|/__/ \__|            ##
##                   All Features shown in your Server-List!                   ##
##  -------------------------------------------------------------------------  ##
server-list:

  # If the ServerList module is enabled or not.
  enabled: true

  # Sets if a custom MotD (Message of the Day) is enabled.
  custom-motd: false

  # A list of all possible MotD that can be shown to the user, if custom-motd is enabled.
  # You can use the MiniMessage syntax for custom styling: https://docs.advntr.dev/minimessage/format.html
  custom-motd-messages:
    - "A simple MotD without any formatting!"
    - "<yellow>Another <red>example <black>MotD, <green>but <blue>with <white>colors."
    - "A third example with <rainbow>a fancy rainbow</rainbow>. You can add as many as you want."

  # Sets if custom favicons (server icons) are enabled.
  # Custom favicons are currently unstable and experimental. Use at your own risk!
  custom-favicon: false

  # A list of all possible favicons (server icons) that can be shown to the user, if custom-favicon is enabled.
  # Resolution has to be 128x128 pixels. Didn't find any good example image, so I just put some weird thing.
  # Custom favicons are currently unstable and experimental. Use at your own risk!
  custom-favicon-urls:
    - https://marcpg.com/pooper/example_server-icon.png

  # Sets the maximum player count that should be shown.
  #   Set to -1 to pass through velocity's max players. (Default)
  #   Set to -2 to always show the current player count + 1.
  show-max-players: -1

  # Sets a fake player count that should be shown. Shouldn't be used on honest servers.
  # Can seriously harm your server community's trust!
  #   Set to -1 to pass through velocity's real player count. (Default)
  #   Set to -2 to hide the player count.
  show-current-players: -1




##  -------------------------------------------------------------------------  ##
##          __   __     _             __  __  _        _                       ##
##          \ \ / /___ (_) _ _   ___ |  \/  |(_) _ _  (_) _ _   __ _           ##
##           \ V // -_)| || ' \ |___|| |\/| || || ' \ | || ' \ / _` |          ##
##            \_/ \___||_||_||_|     |_|  |_||_||_||_||_||_||_|\__, |          ##
##                     The optional Better-Mining Feature.     |___/           ##
##  -------------------------------------------------------------------------  ##
# Vein-Mining will allow you to only break one block from an ore-vein,
# which will result in the whole vein being destroyed.
vein-mining:
  # If the Vein-Mining module is enabled or not.
  enabled: false

  # Sets if you will need to use the right tool, for the vein mining to work.
  require-proper-tool: true

  # Sets if the vein will be destroyed with a little animation, which just
  # makes the blocks be destroyed with a little delay between each block.
  animated: true

  # The maximum distance (radius) in blocks from the initially broken block
  # that the vein will be destroyed.
  max-distance: 10

  # If this is enabled, all default ores in Minecraft will automatically be
  # added to the 'ores' list. This contains all materials ending with "_ore".
  auto-fill-ores: true

  # A list of all materials that will be counted as a vein. See 'auto-fill'!
  # Materials here should not contain the namespace (e.g. "minecraft:")!
  ores:
    - example_ore




##  -------------------------------------------------------------------------  ##
##                      ___            _                                       ##
##                     | _ ) __ _  __ | |___  _  _ __  ___                     ##
##                     | _ \/ _` |/ _|| / / || || '_ \(_-<                     ##
##                     |___/\__,_|\__||_\_\\_,_|| .__//__/                     ##
##                     The simple & easy backup |_| feature.                   ##
##  -------------------------------------------------------------------------  ##
backups:
  # If the backup module is enabled or not.
  enabled: false

  # The interval between each backup. Should only be one time unit.
  interval: 30min

  # The method to store the backups.
  #   Available Methods:
  #     | -> local        : on your local machine
  #     | -> google-drive : on Google Drive (https://drive.google.com/)
  #     | -> onedrive     : on Microsoft OneDrive (https://onedrive.live.com/)
  #     | -> database     : on the same database as all other data. Requires the 'storage-method' to be 'database'
  storage-method: yaml




##  -------------------------------------------------------------------------  ##
##                     __  __          _        _                              ##
##                    |  \/  | ___  __| | _  _ | | ___  ___                    ##
##                    | |\/| |/ _ \/ _` || || || |/ -_)(_-<                    ##
##                    |_|  |_|\___/\__,_| \_,_||_|\___|/__/                    ##
##                Completely optional and configurable modules.                ##
##  -------------------------------------------------------------------------  ##
modules:

  # ------------------------------------------------------------------------- #
  #                              NO ANVIL XP CAP                              #
  #            Removes the Anvil XP Cap when enchanting/repairing.            #
  # ------------------------------------------------------------------------- #
  no-anvil-cap: false

  # ------------------------------------------------------------------------- #
  #                               DEATH BANNING                               #
  #        Bans players automatically whenever they die or get killed.        #
  # ------------------------------------------------------------------------- #
  death-banning:

    # If the Death-Banning module is enabled or not.
    enabled: false

    # Will only ban a player if they got killed by someone else and ignore
    # the death, if it was caused by something else.
    only-killing: false

    # If the death message should be included in the ban/kick screen.
    show-death-message: true

    # How long the player will be banned for. Should only use one time unit.
    #   Set to "kick" to kick instead of ban.
    #   Set to "permanent" to ban permanently.
    duration: 1h

  # ------------------------------------------------------------------------ #
  #                                  MOB AI                                  #
  #           Slightly improves the AI of most mobs on the server.           #
  # ------------------------------------------------------------------------ #
  better-mob-ai:

    # If the Better-Mob-AI module is enabled or not.
    enabled: false

    # Makes groups of friendly mobs, like cows or sheep, all be alerted
    # and flee together, if one of them gets hit.
    panicking-groups: true

    # Gives normally friendly mobs the ability to protect themselves, if you attack them.
    # Not implemented yet!
    fighting-instinct: false

    # Configures the various mobs that can have improved AI.
    # Not implemented yet!
    mobs:
      example: true

  # ------------------------------------------------------------------------ #
  #                               BETTER SLEEP                               #
  #                   Improves how the sleep system works.                   #
  # ------------------------------------------------------------------------ #
  # Not implemented yet!
  better-sleep:

    # If the Better-Sleep module is enabled or not.
    # Not implemented yet!
    enabled: false

    # How the night will go by.
    #   Available Modes:
    #     | -> default     : will skip the night like in vanilla, so an instant time skip.
    #     | -> sprint      : will just increase how fast time goes by if sleeping.
    #     | -> full_sprint : will increase the whole game, also making player and mob speed increase.
    #     | -> time_set    : will constantly set the time a certain amount later, to give the illusion of time going by.
    # Not implemented yet!
    mode: sprint

    # How much faster the night will go. In vanilla, the night will be about 12 minutes.
    # Setting it to 2.0 will reduce this to 6 minutes. Default: 24.0 (30 seconds)
    # Not implemented yet!
    realistic-sleep-multiplier: 24.0

    # The required percentage of players who need to sleep in a world, for the night to be skipped.
    # Not implemented yet!
    players-required: 100.0




## DO NOT CHANGE THIS! ##
version: 8
